### ISSUE TITLE
Vote Buttons: Hovering a button moves it above the selection indicator

### ISSUE THREAD

**Issue by He3lixxx** [e-valuation/EvaP#1611]
![image](https://user-images.githubusercontent.com/13838962/127904877-0e8bc055-d69d-49d0-b82d-36454f4b7862.png)
"Agree" is active / selected
"Neutral" is hovered

This could be fixed by adding a `z-index=2` to any active buttons (to move it just above all non-selected buttons) (probably in static/scss/components/_buttons.scss):
```scss
.btn:not(:disabled):not(.disabled).active {
    z-index: 2;  // The box shadow should be above the other buttons (even if they are hovered)
}
```
(see https://github.com/twbs/bootstrap/blob/main/scss/_buttons.scss#L35 for the selector they apply)
but since it could be considered a bug in bootstrap, it might be resolved by simply updating bootstrap (which we have to do anyway).

@pixunil I think you worked on this or something similar in the past, what was the outcome of that?
