### ISSUE TITLE
Run a CI workflow where dev dependencies are not installed

### ISSUE THREAD

**Issue by niklasmohrin** [e-valuation/EvaP#2113]
After #2110, I think that at least one of our CI workflows should run without the dev dependencies installed. @Kakadus said that it is probably possible, we may want to get rid of the dependency of the virtualenv cache action and use `actions/cache` ourselves.

I think the backup process workflow is suited for this, so we don't need to add an extra workflow.

The goal I have in mind is the possibility of the following:
```yaml
- name: Setup python
  uses: ./.github/setup_python
  with:
    install-dev-requirements: false
```
and our `setup_python` does the right thing :^)
